version: '3'
services:
  video-streaming:
    image: video-streaming
    build:
      dockerfile: Dockerfile
      context: ./video-streaming
    container_name: video-streaming
    ports:
      - "4000:80"

    environment:
      - PORT=80

    restart: "no"
